package org.apache.jsp.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.Echarge.admin.*;
import com.Echarge.Role.*;
import java.util.*;

public final class Admin_005fAddUser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html;charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	//检查session，查看用户是否登陆
	Admin a = (Admin) session.getAttribute("admin");
	if (a == null) {
		response.sendRedirect("../Admin_Login.jsp");
		return;
	}

      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("GBK");
	String action = request.getParameter("action");
	if (action != null && action.trim().equals("newAdmin")) {
		String adminName = request.getParameter("adminName");
		String loginName = request.getParameter("loginName");
		String loginPwd = request.getParameter("loginPwd");
		String adminEmail = request.getParameter("adminEmail");
		String phoneNum = request.getParameter("phoneNum");
		String adminAddress = request.getParameter("adminAddress");
		String adminType = request.getParameter("adminType");
		try {
			a = Admin.checkName1(loginName);
		} catch (UserNotFoundException e) {
			out.println(e.getMessage());
			return;
		}
		a.setAdminName(adminName);
		a.setLoginName(loginName);
		a.setLoginPwd(loginPwd);
		a.setAdminEmail(adminEmail);
		a.setPhoneNum(phoneNum);
		a.setAdminAddress(adminAddress);
		a.setAdminType(adminType);
		a.setAddDate(new Date());
		a.save();
		response.sendRedirect("Admin_UserList.jsp");
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>Echarge 管理中心 - 添加用户</title>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\" />\r\n");
      out.write("\t\t<link href=\"../css/login.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t<link href=\"../css/page_bottom.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../js/jquery-1.4.2.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../js/jquery.validate.js\"></script>\r\n");
      out.write("\t\t<link href=\"styles/main.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t<link href=\"styles/general.css\" rel=\"stylesheet\" type=\"text/css\" />\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t$('#f').validate( {\r\n");
      out.write("\t\t\trules : {\r\n");
      out.write("\t\t\t\tadminName : {\r\n");
      out.write("\t\t\t\t\trequired : true,\r\n");
      out.write("\t\t\t\t\trangelength : [ 2, 4 ]\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tloginName1 : {\r\n");
      out.write("\t\t\t\t\trequired : true,\r\n");
      out.write("\t\t\t\t\trangelength : [ 3, 12 ]\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tloginPwd : {\r\n");
      out.write("\t\t\t\t\trequired : true,\r\n");
      out.write("\t\t\t\t\trangelength : [ 4, 20 ]\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tcheckPwd : {\r\n");
      out.write("\t\t\t\t\trequired : true,\r\n");
      out.write("\t\t\t\t\trangelength : [ 4, 20 ],\r\n");
      out.write("\t\t\t\t\tequalTo : \"#txtPassword\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tphoneNum:{\r\n");
      out.write("\t\t\t\t\trequired:true,\r\n");
      out.write("\t\t\t\t\trangelength:[11,11],\r\n");
      out.write("\t\t\t\t\tdigits:true\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tadminEmail:{\r\n");
      out.write("\t\t\t\t\temail:true\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tadminType:{\r\n");
      out.write("\t\t\t\t\trequired:true\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tmessages : {\r\n");
      out.write("\t\t\t\tadminName : {\r\n");
      out.write("\t\t\t\t\trequired : \"真实姓名不能为空\",\r\n");
      out.write("\t\t\t\t\trangelength : \"真实姓名应为2-4位之间\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tloginName1 : {\r\n");
      out.write("\t\t\t\t\trequired : \"账号不能为空\",\r\n");
      out.write("\t\t\t\t\trangelength : \"账号应为3-12位之间\",\r\n");
      out.write("\t\t\t\t\tremote : \"账号已被占用\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tloginPwd : {\r\n");
      out.write("\t\t\t\t\trequired : \"密码不能为空\",\r\n");
      out.write("\t\t\t\t\trangelength : \"密码应为4-20位之间\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tcheckPwd : {\r\n");
      out.write("\t\t\t\t\trequired : \"密码不能为空\",\r\n");
      out.write("\t\t\t\t\trangelength : \"密码应为4-20位之间\",\r\n");
      out.write("\t\t\t\t\tequalTo : \"两次密码不一致\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tphoneNum:{\r\n");
      out.write("\t\t\t\t\trequired:\"手机号码不能为空\",\r\n");
      out.write("\t\t\t\t\trangelength:\"手机号码格式错误\",\r\n");
      out.write("\t\t\t\t\tdigits:\"必须是整数数字\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tadminEmail:{\r\n");
      out.write("\t\t\t\t\temail : \"请输入正确的email格式\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tadminType:{\r\n");
      out.write("\t\t\t\t\trequired:\"请选择用户类型\"\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terrorPlacement : function(error, element) {\r\n");
      out.write("\t\t\t\terror.appendTo(element.next().find(\"span\"));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\t//定义一个变量用于存放XMLHttpRequest对象\r\n");
      out.write("\tvar xmlHttp; \r\n");
      out.write("\t\r\n");
      out.write("\t//该函数用于创建一个XMLHttpRequest对象\r\n");
      out.write("\tfunction createXMLHttpRequest() {\r\n");
      out.write("\t\tif (window.ActiveXObject) {\r\n");
      out.write("\t\t\txmlHttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\telse if (window.XMLHttpRequest) {\r\n");
      out.write("\t\t\txmlHttp = new XMLHttpRequest();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t//这是一个启动AJAX异步通信的方法\r\n");
      out.write("\tfunction beginCheck(){\r\n");
      out.write("\t\tvar tempLoginName = document.form1.loginName.value;\r\n");
      out.write("\t\tif (tempLoginName == \"\"){//如果尚未输入注册名\r\n");
      out.write("\t\t \talert(\"对不起，请您输入注册名!\");\r\n");
      out.write("\t\t \treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//创建一个XMLHttpRequest对象\r\n");
      out.write("\t\tcreateXMLHttpRequest();\r\n");
      out.write("\t\t//将状态触发器绑定到一个函数\r\n");
      out.write("\t\txmlHttp.onreadystatechange = processor;\r\n");
      out.write("\t\t//通过GET方法向指定的URL建立服务器的调用\r\n");
      out.write("\t\txmlHttp.open(\"GET\", \"AdminCheckServlet?loginName=\"+tempLoginName);\r\n");
      out.write("\t\t//发送请求\r\n");
      out.write("\t\txmlHttp.send(null);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//这是一用来处理状态改变的函数\r\n");
      out.write("\tfunction processor () {\r\n");
      out.write("\t\t//定义一个变量用于存放从服务器返回的响应结果\r\n");
      out.write("\t\tvar responseContext;\r\n");
      out.write("\t\tif(xmlHttp.readyState == 4) { //如果响应完成\r\n");
      out.write("\t\t\tif(xmlHttp.status == 200) {//如果返回成功\r\n");
      out.write("\t\t\t\t//取出服务器的响应内容\r\n");
      out.write("\t\t\t\tresponseContext = xmlHttp.responseText;\r\n");
      out.write("\t\t\t\t//如果注册名检查有效\r\n");
      out.write("\t\t\t\tif (responseContext.indexOf(\"true\")!=-1){\r\n");
      out.write("\t\t\t\t\talert(\"恭喜您，该注册名有效！\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\talert(\"对不起，该注册名已被使用！\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t\t<script language=\"javascript\">\r\n");
      out.write("\t\t<!--start_of_saved_settings-->\r\n");
      out.write("<!--type,text,name,adminName,required,true,errMsg,真实姓名不能为空!-->\r\n");
      out.write("<!--type,text,name,loginName,required,true,errMsg,账号不能为空!-->\r\n");
      out.write("<!--type,password,name,loginPwd,required,true,errMsg,密码不能为空!-->\r\n");
      out.write("<!--type,password,name,checkPwd,required,true,errMsg,确认密码不能为空!-->\r\n");
      out.write("<!--type,text,name,phoneNum,required,true,errMsg,电话不能为空!-->\r\n");
      out.write("<!--type,text,name,adminAddress,required,true,errMsg,地址不能为空!-->\r\n");
      out.write("<!--end_of_saved_settings-->\r\n");
      out.write("document.form1.adminName.focus;\r\n");
      out.write("function CheckForm(){\r\n");
      out.write(" var theform = document.form1;\r\n");
      out.write(" //var errMsg = \"\";\r\n");
      out.write(" //var setfocus = \"\";\r\n");
      out.write(" \r\n");
      out.write(" if (theform['adminName'].value == \"\") {\r\n");
      out.write("    alert(\"真实姓名不能为空!\");\r\n");
      out.write("  \ttheform.adminName.focus();\r\n");
      out.write("  \treturn false;\r\n");
      out.write(" }\r\n");
      out.write(" if (theform['loginName'].value == \"\") {\r\n");
      out.write("    alert(\"账号不能为空!\");\r\n");
      out.write("  \ttheform.loginName.focus();\r\n");
      out.write("  \treturn false;\r\n");
      out.write(" }\r\n");
      out.write(" if (theform['loginPwd'].value == \"\") {\r\n");
      out.write("    alert(\"密码不能为空!\");\r\n");
      out.write("  \ttheform.loginPwd.focus();\r\n");
      out.write("  \treturn false;\r\n");
      out.write(" }\r\n");
      out.write(" if (theform['checkPwd'].value == \"\") {\r\n");
      out.write("    alert(\"确认密码不能为空!\");\r\n");
      out.write("  \ttheform.checkPwd.focus();\r\n");
      out.write("  \treturn false;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" if (theform['loginPwd'].value != theform['checkPwd'].value) {\r\n");
      out.write("    alert(\"两次密码输入不一致!\");\r\n");
      out.write("  \ttheform.loginPwd.focus();\r\n");
      out.write("  \treturn false;\r\n");
      out.write(" }\r\n");
      out.write(" return true;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<table style=\"table-layout: fixed;\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"97%\">\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"nav\" align=\"left\" nowrap=\"nowrap\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t<h1>\r\n");
      out.write("\t\t\t<span class=\"action-span\"></span><span>Echarge 管理中心  - 添加用户</span>\r\n");
      out.write("\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"fill_message\">\r\n");
      out.write("\t\t\t<form name=\"form1\" method=\"post\" action=\"Admin_AddUser.jsp\" id=\"f\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"action\" value=\"newAdmin\" />\r\n");
      out.write("\t\t\t\t<table class=\"tab_login\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td valign=\"top\" class=\"w1\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"mcname\" style=\"color:red\">*</span>\r\n");
      out.write("\t\t\t\t\t\t\t用户账号:\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"loginName\" type=\"text\" id=\"txtLoginName\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"text_input\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text_left\"><input type=\"button\" name=\"checkLoginName\" value=\"有效性检查\" \r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width:80px\" onclick=\"beginCheck()\"/></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text_left\" id=\"loginNameValidMsg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t用户账号可以由小写英文字母、中文、数字组成。\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td valign=\"top\" class=\"w1\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"mcname\" style=\"color:red\">*</span>\r\n");
      out.write("\t\t\t\t\t\t\t用户真实姓名:\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"adminName\" type=\"text\" id=\"txtAdminName\" class=\"text_input\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text_left\" id=\"adminNameValidMsg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t真实姓名可以由中文组成，长度2－4个字符，一个汉字为一个字符。\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"name.info\" style=\"color: red\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td valign=\"top\" class=\"w1\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"mcname\" style=\"color:red\">*</span>\r\n");
      out.write("\t\t\t\t\t\t\t设置密码：\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"loginPwd\" type=\"password\" id=\"txtPassword\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"text_input\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text_left\" id=\"passwordValidMsg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t您的密码可以由大小写英文字母、数字组成，长度4－20位。\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"password.info\" style=\"color: red\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td valign=\"top\" class=\"w1\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"mcname\" style=\"color:red\">*</span>\r\n");
      out.write("\t\t\t\t\t\t\t再次输入您设置的密码：\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"checkPwd\" type=\"password\" id=\"txtRepeatPass\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"text_input\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text_left\" id=\"repeatPassValidMsg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"password1.info\" style=\"color: red\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td valign=\"top\" class=\"w1\">\r\n");
      out.write("\t\t\t\t\t\t\t请填写您的Email地址：\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"adminEmail\" type=\"text\" id=\"txtadminEmail\" class=\"text_input\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text_left\" id=\"adminEmailValidMsg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t请填写有效的Email地址。\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"name.info\" style=\"color: red\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td valign=\"top\" class=\"w1\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"mcname\" style=\"color:red\">*</span>\r\n");
      out.write("\t\t\t\t\t\t\t请填写您的手机号码:\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"phoneNum\" type=\"text\" id=\"txtphoneNum\" class=\"text_input\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text_left\" id=\"phoneNumValidMsg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t电话必须由整数数字组成，长度11个字符。\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"name.info\" style=\"color: red\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td valign=\"top\" class=\"w1\">\r\n");
      out.write("\t\t\t\t\t\t\t请填写您的住址:\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"adminAddress\" type=\"text\" id=\"txtadminAddress\" class=\"text_input\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text_left\" id=\"adminAddressValidMsg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t住址可以由小写英文字母、中文、数字组成。\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"name.info\" style=\"color: red\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td valign=\"top\" class=\"w1\">\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"mcname\" style=\"color: red\">*</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t用户类型:\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"adminType\"  class=\"text_input\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t请选择\r\n");
      out.write("\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									List<Role> roles = new ArrayList<Role>();
									Role.getRoles(roles, 1, 10);
									for (int i = 0; i < roles.size(); i++) {
										Role r = roles.get(i);
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"");
      out.print(r.getRoleName());
      out.write('"');
      out.write('>');
      out.print(r.getRoleName());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text_left\" id=\"adminTypeValidMsg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;请选择正确的用户类型，不同类型的用户具有不同的权限\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"name.info\" style=\"color: red\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t<table align=\"center\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"提交\"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<input type=\"reset\" value=\"重填\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
